on:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.6.12

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: 安装依赖
        run: pnpm install

      - name: 构建 VitePress
        run: |
          pnpm run docs:build
          touch .vitepress/dist/.nojekyll

      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3  # 显式使用 v3 版本
        with:
          path: .vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3  # 统一使用 v3 版本
